Sales forcast prediction

In [119]:
# imports
import pandas as pd
import numpy as np

In [120]:
data = pd.read_csv("train.csv")
df = pd.DataFrame(data)

In [121]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [146]:
new_data = pd.DataFrame(df[['Order Date','Segment','Region','Category','Sub-Category','Sales','Ship Date','Product Name']])

In [147]:
new_data.head()

,Order Date,Segment,Region,Category,Sub-Category,Sales,Ship Date,Product Name
0,08/11/2017,Consumer,South,Furniture,Bookcases,261.9600,11/11/2017,Bush Somerset Collection Bookcase
1,08/11/2017,Consumer,South,Furniture,Chairs,731.9400,11/11/2017,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,12/06/2017,Corporate,West,Office Supplies,Labels,14.6200,16/06/2017,Self-Adhesive Address Labels for Typewriters b...
3,11/10/2016,Consumer,South,Furniture,Tables,957.5775,18/10/2016,Bretford CR4500 Series Slim Rectangular Table
4,11/10/2016,Consumer,South,Office Supplies,Storage,22.3680,18/10/2016,Eldon Fold 'N Roll Cart System

In [148]:
new_data.head(50)

,Order Date,Segment,Region,Category,Sub-Category,Sales,Ship Date,Product Name
0,08/11/2017,Consumer,South,Furniture,Bookcases,261.9600,11/11/2017,Bush Somerset Collection Bookcase
1,08/11/2017,Consumer,South,Furniture,Chairs,731.9400,11/11/2017,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,12/06/2017,Corporate,West,Office Supplies,Labels,14.6200,16/06/2017,Self-Adhesive Address Labels for Typewriters b...
3,11/10/2016,Consumer,South,Furniture,Tables,957.5775,18/10/2016,Bretford CR4500 Series Slim Rectangular Table
4,11/10/2016,Consumer,South,Office Supplies,Storage,22.3680,18/10/2016,Eldon Fold 'N Roll Cart System
5,09/06/2015,Consumer,West,Furniture,Furnishings,48.8600,14/06/2015,Eldon Expressions Wood and Plastic Desk Access...
6,09/06/2015,Consumer,West,Office Supplies,Art,7.2800,14/06/2015,Newell 322
7,09/06/2015,Consumer,West,Technology,Phones,907.1520,14/06/2015,Mitel 5320 IP Phone VoIP phone
8,09/06/2015,Consumer,West,Office Supplies,Binders,18.5040,14/06/2015,DXL Angle-View Binders with Locking Rings by S...
9,09/06/2015,Consumer,West,Office Supplies,Appliances,114.9000,14/06/2015,Belkin F5C206VTEL 6 Outlet Surge
10,09/06/2015,Consumer,West,Furniture,Tables,1706.1840,14/06/2015,Chromcraft Rectangular Conference Tables
11,09/06/2015,Consumer,West,Technology,Phones,911.4240,14/06/2015,Konftel 250 Conference phone - Charcoal black
12,15/04/2018,Consumer,South,Office Supplies,Paper,15.5520,20/04/2018,Xerox 1967
13,05/12/2017,Consumer,West,Office Supplies,Binders,407.9760,10/12/2017,Fellowes PB200 Plastic Comb Binding Machine
14,22/11/2016,Home Office,Central,Office Supplies,Appliances,68.8100,26/11/2016,Holmes Replacement Filter for HEPA Air Cleaner...
15,22/11/2016,Home Office,Central,Office Supplies,Binders,2.5440,26/11/2016,Storex DuraTech Recycled Plastic Frosted Binders
16,11/11/2015,Consumer,Central,Office Supplies,Storage,665.8800,18/11/2015,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x..."
17,13/05/2015,Consumer,West,Office Supplies,Storage,55.5000,15/05/2015,Fellowes Super Stor/Drawer
18,27/08/2015,Consumer,West,Office Supplies,Art,8.5600,01/09/2015,Newell 341
19,27/08/2015,Consumer,West,Technology,Phones,213.4800,01/09/2015,Cisco SPA 501G IP Phone
20,27/08/2015,Consumer,West,Office Supplies,Binders,22.7200,01/09/2015,"Wilson Jones Hanging View Binder, White, 1"""
21,09/12/2017,Corporate,Central,Office Supplies,Art,19.4600,13/12/2017,Newell 318
22,09/12/2017,Corporate,Central,Office Supplies,Appliances,60.3400,13/12/2017,"Acco Six-Outlet Power Strip, 4' Cord Length"
23,16/07/2018,Consumer,East,Furniture,Chairs,71.3720,18/07/2018,"Global Deluxe Stacking Chair, Gray"
24,25/09/2016,Consumer,West,Furniture,Tables,1044.6300,30/09/2016,Bretford CR4500 Series Slim Rectangular Table
25,16/01/2017,Consumer,West,Office Supplies,Binders,11.6480,20/01/2017,Wilson Jones Active Use Binders
26,16/01/2017,Consumer,West,Technology,Accessories,90.5700,20/01/2017,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive
27,17/09/2016,Consumer,East,Furniture,Bookcases,3083.4300,21/09/2016,"Riverside Palais Royal Lawyers Bookcase, Royal..."
28,17/09/2016,Consumer,East,Office Supplies,Binders,9.6180,21/09/2016,Avery Recycled Flexi-View Covers for Binding S...
29,17/09/2016,Consumer,East,Furniture,Furnishings,124.2000,21/09/2016,"Howard Miller 13-3/4"" Diameter Brushed Chrome ..."
30,17/09/2016,Consumer,East,Office Supplies,Envelopes,3.2640,21/09/2016,Poly String Tie Envelopes
31,17/09/2016,Consumer,East,Office Supplies,Art,86.3040,21/09/2016,"BOSTON Model 1800 Electric Pencil Sharpeners, ..."
32,17/09/2016,Consumer,East,Office Supplies,Binders,6.8580,21/09/2016,"Acco Pressboard Covers with Storage Hooks, 14 ..."
33,17/09/2016,Consumer,East,Office Supplies,Art,15.7600,21/09/2016,Lumber Crayons
34,19/10/2018,Home Office,Central,Office Supplies,Paper,29.4720,23/10/2018,Easy-staple paper
35,08/12/2017,Corporate,Central,Technology,Phones,1097.5440,10/12/2017,GE 30524EE4
36,08/12/2017,Corporate,Central,Furniture,Furnishings,190.9200,10/12/2017,"Electrix Architect's Clamp-On Swing Arm Lamp, ..."
37,27/12/2016,Home Office,Central,Office Supplies,Envelopes,113.3280,31/12/2016,"#10-4 1/8"" x 9 1/2"" Premium Diagonal Seam Enve..."
38,27/12/2016,Home Office,Central,Furniture,Bookcases,532.3992,31/12/2016,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust..."
39,27/12/2016,Home Office,Central,Furniture,Chairs,212.0580,31/12/2016,"Global Fabric Manager's Chair, Dark Gray"
40,27/12/2016,Home Office,Central,Technology,Phones,371.1680,31/12/2016,Plantronics HL10 Handset Lifter
41,10/09/2018,Corporate,Central,Technology,Phones,147.1680,15/09/2018,Panasonic Kx-TS550
42,17/07/2017,Corporate,West,Office Supplies,Storage,77.8800,22/07/2017,"Eldon Base for stackable storage shelf, platinum"
43,19/09/2018,Corporate,South,Office Supplies,Storage,95.6160,23/09/2018,"Advantus 10-Drawer Portable Organizer, Chrome ..."
44,11/03/2017,Corporate,Central,Technology,Accessories,45.9800,13/03/2017,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...
45,11/03/2017,Corporate,Central,Office Supplies,Binders,17.4600,13/03/2017,Wilson Jones Leather-Like Binders with DublLoc...
46,20/10/2015,Consumer,Central,Office Supplies,Storage,211.9600,25/10/2015,"Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5..."
47,20/06/2017,Consumer,East,Technology,Accessories,45.0000,25/06/2017,Imation 8gb Micro Traveldrive Usb 2.0 Flash Drive
48,20/06/2017,Consumer,East,Technology,Phones,21.8000,25/06/2017,"LF Elite 3D Dazzle Designer Hard Case Cover, L..."
49,18/04/2016,Consumer,Central,Office Supplies,Binders,38.2200,22/04/2016,"C-Line Peel & Stick Add-On Filing Pockets, 8-3..."

In [149]:
# fro the Oder Date column 
new_data['Order Date'] = pd.to_datetime(new_data['Order Date'],format='%d/%m/%Y')
new_data['Day'] = new_data['Order Date'].dt.day
new_data['Month'] = new_data['Order Date'].dt.month
new_data['Year'] = new_data['Order Date'].dt.year
new_data['DayOFWeek'] = new_data['Order Date'].dt.dayofweek
new_data['Ship Date'] = pd.to_datetime(new_data['Ship Date'],format='%d/%m/%Y')
new_data["shippingDelays"] = (new_data['Ship Date'].dt.day - new_data['Order Date'].dt.day)

In [150]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order Date      9800 non-null   datetime64[ns]
 1   Segment         9800 non-null   object
 2   Region          9800 non-null   object
 3   Category        9800 non-null   object
 4   Sub-Category    9800 non-null   object
 5   Sales           9800 non-null   float64
 6   Ship Date       9800 non-null   datetime64[ns]
 7   Product Name    9800 non-null   object
 8   Day             9800 non-null   int32
 9   Month           9800 non-null   int32
 10  Year            9800 non-null   int32
 11  DayOFWeek       9800 non-null   int32
 12  shippingDelays  9800 non-null   int32
dtypes: datetime64[ns](2), float64(1), int32(5), object(5)
memory usage: 804.0+ KB

In [151]:
new_data.head()

,Order Date,Segment,Region,Category,Sub-Category,Sales,Ship Date,Product Name,Day,Month,Year,DayOFWeek,shippingDelays
0,2017-11-08,Consumer,South,Furniture,Bookcases,261.9600,2017-11-11,Bush Somerset Collection Bookcase,8,11,2017,2,3
1,2017-11-08,Consumer,South,Furniture,Chairs,731.9400,2017-11-11,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",8,11,2017,2,3
2,2017-06-12,Corporate,West,Office Supplies,Labels,14.6200,2017-06-16,Self-Adhesive Address Labels for Typewriters b...,12,6,2017,0,4
3,2016-10-11,Consumer,South,Furniture,Tables,957.5775,2016-10-18,Bretford CR4500 Series Slim Rectangular Table,11,10,2016,1,7
4,2016-10-11,Consumer,South,Office Supplies,Storage,22.3680,2016-10-18,Eldon Fold 'N Roll Cart System,11,10,2016,1,7

In [152]:
new_data.drop(['Order Date'],inplace = True, axis = 1)

In [153]:
new_data.head()

,Segment,Region,Category,Sub-Category,Sales,Ship Date,Product Name,Day,Month,Year,DayOFWeek,shippingDelays
0,Consumer,South,Furniture,Bookcases,261.9600,2017-11-11,Bush Somerset Collection Bookcase,8,11,2017,2,3
1,Consumer,South,Furniture,Chairs,731.9400,2017-11-11,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",8,11,2017,2,3
2,Corporate,West,Office Supplies,Labels,14.6200,2017-06-16,Self-Adhesive Address Labels for Typewriters b...,12,6,2017,0,4
3,Consumer,South,Furniture,Tables,957.5775,2016-10-18,Bretford CR4500 Series Slim Rectangular Table,11,10,2016,1,7
4,Consumer,South,Office Supplies,Storage,22.3680,2016-10-18,Eldon Fold 'N Roll Cart System,11,10,2016,1,7

In [154]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Segment         9800 non-null   object
 1   Region          9800 non-null   object
 2   Category        9800 non-null   object
 3   Sub-Category    9800 non-null   object
 4   Sales           9800 non-null   float64
 5   Ship Date       9800 non-null   datetime64[ns]
 6   Product Name    9800 non-null   object
 7   Day             9800 non-null   int32
 8   Month           9800 non-null   int32
 9   Year            9800 non-null   int32
 10  DayOFWeek       9800 non-null   int32
 11  shippingDelays  9800 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(5), object(5)
memory usage: 727.5+ KB

In [157]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()

for col in ['Segment','Region','Category','Sub-Category','Product Name']:
    new_data[col] = le.fit_transform(new_data[col])

new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Segment         9800 non-null   int64
 1   Region          9800 non-null   int64
 2   Category        9800 non-null   int64
 3   Sub-Category    9800 non-null   int64
 4   Sales           9800 non-null   float64
 5   Ship Date       9800 non-null   datetime64[ns]
 6   Product Name    9800 non-null   int64
 7   Day             9800 non-null   int32
 8   Month           9800 non-null   int32
 9   Year            9800 non-null   int32
 10  DayOFWeek       9800 non-null   int32
 11  shippingDelays  9800 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(5), int64(5)
memory usage: 727.5 KB

In [158]:
x = new_data[['Segment', 'Region', 'Category', 'Sub-Category','Day','Month','Year','DayOFWeek','shippingDelays','Product Name']]
y = new_data['Sales']

In [159]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [172]:
x_train , x_test,y_train ,y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)
x_train.shape, x_test.shape,y_train.shape,y_test.shape

# SubCategory avg
avg_map = y_train.groupby(x_train['Sub-Category']).mean()

x_train['SubCategory_avg_sales'] = x_train['Sub-Category'].map(avg_map)
x_test['SubCategory_avg_sales'] = x_test['Sub-Category'].map(avg_map)

x_test['SubCategory_avg_sales'] = x_test['SubCategory_avg_sales'].fillna(avg_map.mean())

# Product avg
avg_product_map = y_train.groupby(x_train['Product Name']).mean()

x_train['product_avg_sales'] = x_train['Product Name'].map(avg_product_map)
x_test['product_avg_sales'] = x_test['Product Name'].map(avg_product_map)

x_test['product_avg_sales'] = x_test['product_avg_sales'].fillna(avg_product_map.mean())

x_train = x_train.drop('Product Name', axis=1)
x_test = x_test.drop('Product Name', axis=1)

x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 532 to 6179
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Segment                1960 non-null   int64
 1   Region                 1960 non-null   int64
 2   Category               1960 non-null   int64
 3   Sub-Category           1960 non-null   int64
 4   Day                    1960 non-null   int32
 5   Month                  1960 non-null   int32
 6   Year                   1960 non-null   int32
 7   DayOFWeek              1960 non-null   int32
 8   shippingDelays         1960 non-null   int32
 9   SubCategory_avg_sales  1960 non-null   float64
 10  product_avg_sales      1960 non-null   float64
dtypes: float64(2), int32(5), int64(4)
memory usage: 145.5 KB

In [173]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [174]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

lr = LinearRegression()
lr.fit(x_train, y_train)

preds = lr.predict(x_test)

print("MAE:", mean_absolute_error(y_test, preds))
print("MSE:", mean_squared_error(y_test, preds))
print("R2 Score:", r2_score(y_test, preds))

MAE: 155.2824012105242
MSE: 461410.58753352455
R2 Score: 0.3096787487835586

In [175]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()
rf.fit(x_train,y_train)

rf_preds = rf.predict(x_test)

print("MAE:", mean_absolute_error(y_test, rf_preds))
print("MSE:", mean_squared_error(y_test, rf_preds))
print("R2 Score:", r2_score(y_test, rf_preds))

MAE: 158.37626956149174
MSE: 469032.49277389154
R2 Score: 0.29827553588740674

In [176]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

model.fit(x_train, y_train)
xgb_preds = model.predict(x_test)
print("MAE:", mean_absolute_error(y_test, xgb_preds))
print("MSE:", mean_squared_error(y_test, xgb_preds))
print("R2 Score:", r2_score(y_test, xgb_preds))

MAE: 162.70655579177884
MSE: 500535.14435835805
R2 Score: 0.2511440862718418